<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>new</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>20</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>573f793f-b90b-4226-a79c-2137e01e1bb0</testSuiteGuid>
   <testCaseLink>
      <guid>89e7b3af-1a04-472a-94ea-6450596cdaaf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/new</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cbfa804d-dda6-4fa2-af9a-e9074f678d90</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/oaid</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d5f8db08-17fc-4f53-b7ce-f4be9b84acac</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/name</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>cbfa804d-dda6-4fa2-af9a-e9074f678d90</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>id</value>
         <variableId>33c67f6f-94e9-4c84-ac87-b054dd06eb9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d5f8db08-17fc-4f53-b7ce-f4be9b84acac</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>3aee7709-5444-4273-80b9-351bfab67360</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
